### ISSUE TITLE
一点建议~

### ISSUE THREAD

**Issue by kscript** [PUGE/deformation#1]
试了下这个组件，从一个使用者的角度，希望功能可以再扩展下 (当然，也可能是我使用的姿势不对)
比如说我今天的需求:
我是在做一个编辑器时找到的这个组件，我的需求是只可以通过左右边界来改变宽度。
但是试过之后发现，这个需求需要 draggable=true resizable=true。
这样一来就产生了很多副作用，比如它是可以左右拖动(draggable)，自由改变宽高的(resizable)

我简单粗暴的改了下组件代码，添加了对拖动(move: Boolean) 和改变大小(size: Stirng[x, y, both]) 的限制，实现了我想要的效果，供您参考。这里是 [Demo](https://codesandbox.io/s/ym26rl12qz)
我个人觉得这些可以集成到draggable，resizable里，让使用者可以: 左右/上下/自由/禁止 地设置拖动和改变大小

**Comment by PUGE** [comment]
谢谢你的简易 我晚上修改下

**Comment by PUGE** [comment]
@kscript 好了1.0.5版本可以通过将draggable 和 resizable 设置为 2来限制只能在X轴拖动和改变大小 设置为3来限制只能在Y轴拖动和改变大小
